region        = "eu-north-1"
access_key    = "AKIATKGS2Z6VMURRCHEY"
secret_key    = "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"
ami_id        = "ami-071df4a41c6f9ee2e"
instance_type = "t3.micro"
key_name      = "falconbird"
machine_name  = "Nima"
created_by    = "terraform"